server:
  port: 80

#上传图片保存位置git
#uploadDir: /home/jw/community/uploads/
uploadDir: H:/community/uploads/
spring:
  datasource:
    url: jdbc:mysql://jwei.fun:3306/community?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jw
    password: jw123
  #上传文件大小限制
  servlet:
    multipart.max-file-size: 20MB
    multipart.max-request-size: 20MB
#github app
github:
  client:
    id: 63d1a395aceaad8a081c
    secret: 2470cba10d7a5f761ba003361b392de0e6618d80
  redirect:
    uri: http://localhost/callback
#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: fun.jwei.community.model
  mapper-locations: classpath:mapper/*.xml
  table.auto: update
  model.pack: fun.jwei.community.model
  database.type: mysql
#log
logging:
  level:
    fun.jwei.community.mapper: debug
## pagehelper分页插件配置 ##
#标识是哪一种数据库
pagehelper:
  helperDialect: mysql
  #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum: pageNum;pageSize: pageSize;count: countSql;reasonable: reasonable;pageSizeZero: pageSizeZero
  params: count=countSql
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  supportMethodsArguments: true
  #如果 pageSize: 0 就会查询出全部的结果（相当于没有执行分页查询）
  page-size-zero: true